### ISSUE TITLE
Do you plan to release a notebook demo ?

### ISSUE THREAD

**Issue by ooza** [naver-ai/tc-clip#2]

**Comment by ooza** [comment]
Thanks for this great job! I have a small dataset of 30 video clips and I want to make zero-shot action recognition using your model. Do you have a simple demo file that I can use? or could you tell me which function/script/config should I update to work on custom videos?

**Comment by byminji** [comment]
Hi @ooza, thank you for your interest in our work!

I will share a sample notebook demo in the upcoming days. 

But if you want to use your custom datasets before that, please follow the below instructions. (Please also refer to the example instructions for public datasets in [DATASETS.md](https://github.com/naver-ai/tc-clip/blob/main/docs/DATASETS.md)).

1. Put all your custom videos under `/PATH/TO/VIDEOS` folder.
2. Create a **label file** in`tc-clip/labels/custom_dataset_labels.csv`. The format should be like:
```
id,name
0,abseiling
1,air drumming
2,answering questions
3,applauding
...
```
3. Create an **annotation file** that contains a list of video filenames and their corresponding labels in `tc-clip/datasets_splits/custom_dataset_anns.txt`. Each line of the txt file should be `<filename> <class id>`. For example, suppose that we have `aaa.mp4`, `bbb.mp4`, ..., `zzz.mp4` under `/PATH/TO/VIDEOS` folder:
```
aaa.mp4 0
bbb.mp4 0
...
zzz.mp4 3
```
4. Create a **dataset yaml** file for your custom dataset in `tc-clip/configs/data/custom_dataset.yaml`. Below is an example for the inference only case:
```
#@package _global_
data:
  test:
    - name: custom_dataset
      protocol: top1
      dataset_list:
      - dataset_name: custom_dataset
        root: /PATH/TO/VIDEOS
        num_classes: <YOUR_ACTUAL_NUM_CLASSES>
        label_file: tc-clip/labels/custom_dataset_labels.csv
        ann_file: tc-clip/datasets_splits/custom_dataset_anns.txt
```

5. Now run the below command. Note the `data=custom_dataset` part:
```
torchrun --nproc_per_node=4 main.py -cn zero_shot \
data=custom_dataset output=/PATH/TO/OUTPUT \
trainer=tc_clip eval=test resume=/PATH/TO/CHECKPOINTS/zero_shot_k400_tc_clip.pth
```

If you have any follow-up questions, feel free to ask. I will also mention you after adding a sample notebook.
